[project]
name = "recapify"
version = "0.1.0"
description = "Automatic work report every day"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.12.10",
]
